const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../assets/analytics.js'),'utf8');
const ID='G-9CYYFYT8ZY',KEY='ims.analytics-consent.v1';
function harness(options={}) {
  const nodes=[],events={},windowEvents={},storage=new Map(),deleted=[],writes=[];
  let reloads=0,blocked=options.blocked||false;
  if(options.preference!==undefined)storage.set(KEY,typeof options.preference==='string'?options.preference:JSON.stringify(options.preference));
  function element(tag){const el={tagName:tag,hidden:false,disabled:false,textContent:'',children:[],attrs:{},handlers:{},setAttribute(k,v){this.attrs[k]=v;},appendChild(c){c.parent=this;this.children.push(c);nodes.push(c);return c;},addEventListener(k,fn){this.handlers[k]=fn;},focus(){doc.activeElement=this;},remove(){this.removed=true;}};return el;}
  const doc={readyState:'complete',referrer:options.referrer||'https://search.example/results?q=private@example.com',activeElement:null,createElement:element,addEventListener(k,f){events[k]=f;},getElementById(id){return nodes.find(n=>n.id===id&&!n.removed)||null;},querySelector(selector){if(selector==='form, iframe')return options.form?element('form'):null;if(selector.includes('script[src*='))return options.otherTag?element('script'):null;if(selector==='footer .legal'||selector==='footer')return this.footer;return null;}};
  doc.head=element('head');doc.body=element('body');doc.footer=element('footer');
  Object.defineProperty(doc,'cookie',{get(){return options.cookies||'';},set(v){deleted.push(v);}});
  const url=new URL(options.url||'https://imsmethod.com/');
  const win={location:{protocol:url.protocol,hostname:url.hostname,port:url.port,origin:url.origin,pathname:url.pathname,search:url.search,hash:url.hash,reload(){reloads++;}},addEventListener(k,f){windowEvents[k]=f;}};
  if(options.otherGtag)win.gtag=()=>{};
  const context=vm.createContext({window:win,document:doc,navigator:{globalPrivacyControl:!!options.gpc,doNotTrack:options.dnt},localStorage:{getItem(k){if(blocked)throw Error('blocked');return storage.get(k)||null;},setItem(k,v){if(blocked)throw Error('blocked');storage.set(k,v);writes.push(v);}},URL,URLSearchParams,Date,Number,Object,JSON});
  vm.runInContext(source,context);
  const byId=id=>doc.getElementById(id);
  return {win,doc,storage,deleted,writes,nodes,windowEvents,events,byId,click(id){const e=byId(id);assert.ok(e,'button exists: '+id);if(!e.disabled)e.handlers.click();},script(){return byId('ims-google-analytics');},queue(){return (win.dataLayer||[]).map(v=>Array.from(v));},rerun(){vm.runInContext(source,context);},reloads:()=>reloads,setBlocked(v){blocked=v;}};
}
const grant=()=>({choice:'granted',expires:Date.now()+86400000});
test('no analytics script, queue or cookies before explicit opt-in',()=>{const h=harness();assert.equal(h.script(),null);assert.equal(h.win.dataLayer,undefined);assert.equal(h.win['ga-disable-'+ID],true);assert.equal(h.byId('ims-analytics-preferences').hidden,false);assert.equal(h.writes.length,0);});
test('decline does not load Google or interfere with site use',()=>{const h=harness();h.click('ims-analytics-deny');assert.equal(h.script(),null);assert.equal(h.win.dataLayer,undefined);assert.equal(h.byId('ims-analytics-preferences').hidden,true);assert.equal(JSON.parse(h.storage.get(KEY)).choice,'denied');h.click('ims-analytics-open');assert.equal(h.byId('ims-analytics-preferences').hidden,false);});
test('opt-in creates one tag with ordered consent and analytics-only configuration',()=>{const h=harness();h.click('ims-analytics-allow');assert.equal(h.script().src,'https://www.googletagmanager.com/gtag/js?id='+ID);assert.equal(h.script().referrerPolicy,'no-referrer');const q=h.queue();assert.equal(q.length,4);assert.deepEqual(q[0].slice(0,2),['consent','default']);assert.equal(q[0][2].analytics_storage,'denied');assert.equal(q[1][2].analytics_storage,'granted');for(const key of ['ad_storage','ad_user_data','ad_personalization'])assert.equal(q[1][2][key],'denied');assert.equal(q[3][0],'config');assert.equal(q[3][1],ID);assert.equal(q[3][2].allow_google_signals,false);assert.equal(q[3][2].allow_ad_personalization_signals,false);assert.equal(q[3][2].cookie_domain,'none');assert.equal(q[3][2].page_referrer,'https://search.example/');assert.equal(q[3][2].page_location,'https://imsmethod.com/');assert.equal(JSON.stringify(q).includes('private@example.com'),false);});
test('repeat activation and repeated shared includes do not double-count pageviews',()=>{const h=harness();h.click('ims-analytics-allow');h.click('ims-analytics-allow');h.rerun();assert.equal(h.nodes.filter(n=>n.id==='ims-google-analytics').length,1);assert.equal(h.queue().filter(q=>q[0]==='config').length,1);assert.equal(h.nodes.filter(n=>n.id==='ims-analytics-open').length,1);});
test('saved valid consent works; expired, malformed and extreme-future consent fail closed',()=>{assert.ok(harness({preference:grant()}).script());for(const p of ['bad',{choice:'true',expires:Date.now()+86400000},{choice:'granted',expires:1},{choice:'granted',expires:Date.now()+999999999999}])assert.equal(harness({preference:p}).script(),null);});
test('Google is blocked on private/sensitive routes, previews, foreign hosts and forms',()=>{for(const url of ['https://imsmethod.com/self-check.html','https://imsmethod.com/contact.html','https://imsmethod.com/book.html','https://imsmethod.com/rent-space.html','https://imsmethod.com/clients/person','https://imsmethod.com/api/result','https://coachos-opal.vercel.app/','https://ims-preview.vercel.app/','http://imsmethod.com/','https://imsmethod.com:444/','https://imsmethod.com.evil.test/'])assert.equal(harness({url,preference:grant()}).script(),null,url);assert.equal(harness({form:true,preference:grant()}).script(),null);});
test('unknown paths cannot enter analytics page titles or locations',()=>{const h=harness({url:'https://imsmethod.com/private@example.com',preference:grant()});assert.equal(h.script(),null);assert.equal(h.win.dataLayer,undefined);});
test('query parameters and hashes are blocked except exact approved campaign labels',()=>{for(const suffix of ['?email=private@example.com','#assessment-result','?utm_source=google&email=x','?utm_source=google&utM_medium=organic','?utm_source=google&utm_source=google','?utm_campaign=private_person_name','?gclid=unverified'])assert.equal(harness({url:'https://imsmethod.com/'+suffix,preference:grant()}).script(),null);const h=harness({url:'https://imsmethod.com/?utm_source=google&utm_medium=organic&utm_campaign=gbp_profile',preference:grant()});assert.ok(h.script());assert.equal(h.queue()[3][2].page_location,'https://imsmethod.com/');});
test('GPC and DNT override stored consent and block the allow control',()=>{for(const opt of [{gpc:true},{dnt:'1'}]){const h=harness({...opt,preference:grant()});assert.equal(h.script(),null);assert.equal(h.byId('ims-analytics-allow').disabled,true);h.click('ims-analytics-allow');assert.equal(h.script(),null);}});
test('withdrawal disables collection, clears only our cookies and reloads to unload Google',()=>{const h=harness({preference:grant(),cookies:'ims_ga4=one; ims_ga4_9CYYFYT8ZY=two; session=keep; other_analytics=keep'});h.click('ims-analytics-deny');assert.equal(h.win['ga-disable-'+ID],true);assert.equal(h.script(),null);assert.equal(h.reloads(),1);assert.equal(h.deleted.length,2);assert.ok(h.deleted.every(x=>x.startsWith('ims_ga4')));assert.equal(JSON.parse(h.storage.get(KEY)).choice,'denied');});
test('blocked preference storage permits explicit page consent only and explains the limitation',()=>{const h=harness({blocked:true});h.click('ims-analytics-allow');assert.ok(h.script());assert.match(h.byId('ims-analytics-status').textContent,/only to this page/);assert.equal(h.byId('ims-analytics-preferences').hidden,false);});
test('existing tags are not replaced or duplicated',()=>{for(const flags of [{otherTag:true},{otherGtag:true}]){const h=harness({...flags,preference:grant()});assert.equal(h.script(),null);assert.match(h.byId('ims-analytics-status').textContent,/second copy/);}});
test('failed loader stays failed without automatic retry or false delivery claim',()=>{const h=harness({preference:grant()});h.script().onerror();assert.equal(h.script(),null);assert.equal(h.win['ga-disable-'+ID],true);h.click('ims-analytics-allow');assert.equal(h.script(),null);h.click('ims-analytics-open');assert.match(h.byId('ims-analytics-status').textContent,/failed to load/);});
test('cross-tab revocation and browser restored pages stop collection',()=>{for(const mode of ['storage','pageshow']){const h=harness({preference:grant()});h.storage.delete(KEY);h.windowEvents[mode](mode==='storage'?{key:KEY}:{persisted:true});assert.equal(h.reloads(),1);assert.equal(h.win['ga-disable-'+ID],true);}});
test('no user identity, health results, free text or fabricated conversion events are read',()=>{assert.doesNotMatch(source,/\.value\b|FormData|sendBeacon|\buser_id\s*:|\buser_data\s*:|generate_lead|purchase|ims_cta_click/);assert.match(source,/analytics_storage: 'denied'/);assert.match(source,/ad_personalization: 'denied'/);});
