const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=p=>fs.readFileSync(p,'utf8');
const source=read('api/contact.js').replace("import { createHash } from 'node:crypto';","const { createHash } = require('node:crypto');").replace('export default async function handler','async function handler');
async function contact(env={},method='GET',body={}){const calls=[];const c={require,Buffer,URL,AbortSignal,process:{env:{VERCEL_ENV:'production',RESEND_API_KEY:'synthetic',RESEND_FROM_EMAIL:'synthetic@example.invalid',...env}},console:{error(){},info(){},warn(){}},fetch:async(...args)=>{calls.push(args);throw Error('No real provider allowed');}};vm.createContext(c);vm.runInContext(source+';this.handler=handler;',c);const out={};const res={setHeader(){return this;},status(code){out.status=code;return this;},json(data){out.body=data;return this;}};await c.handler({method,body,headers:{origin:'https://imsmethod.com'}},res);return {out,calls};}
test('production direct contact is off without its explicit gate even when keys exist',async()=>{const r=await contact();assert.equal(r.out.body.direct_delivery,false);assert.equal(r.calls.length,0);const p=await contact({},'POST',{name:'Synthetic Test',email:'synthetic@example.invalid',message:'Do not send this.'});assert.equal(p.out.status,503);assert.equal(p.calls.length,0);});
test('public readiness reveals a boolean only and never proves delivery',async()=>{const r=await contact({IMS_CONTACT_SEND_ENABLED:'true'});assert.deepEqual(Object.keys(r.out.body),['direct_delivery']);assert.equal(r.out.body.direct_delivery,true);assert.equal(r.calls.length,0);});
test('public form remains Web3Forms until runtime configuration enables enhancement',()=>{assert.match(read('contact.html'),/action="https:\/\/api.web3forms.com\/submit"/);const client=read('assets/contact.js');assert.match(client,/direct_delivery === true/);assert.match(client,/receipt\.ok === true/);assert.match(client,/body: pending/);assert.doesNotMatch(client,/localStorage|sessionStorage|location\.href\s*=/);});
test('merged release retains SEO, phone options and affirmative self-check consent',()=>{assert.match(read('coaching.html'),/Private Strength &amp; Mobility Coaching/);assert.match(read('book.html'),/booking-options-heading/);assert.match(read('book.html'),/Personal Training Consultation/);assert.match(read('self-check.html'),/name="self_check_share_consent"[^>]*required/);});
test('chat metrics never read transcript or input content and retain preset ordering',()=>{const m=read('assets/chatbot-metrics.js');assert.doesNotMatch(m,/textContent|innerHTML|\.value\b|JSON\.parse|fetch\(|sendBeacon|localStorage|sessionStorage/);const widget=read('assets/js/chatbot.js');const a=widget.indexOf("'What happens at the free assessment?'"),b=widget.indexOf("'How much does coaching cost?'"),c=widget.indexOf("'What is in the Recovery Room?'");assert.ok(a>0&&b>a&&c>b);assert.match(widget,/history\.slice\(-8\)/);});
